# Prometheus конфигурация для 2GC CloudBridge QUIC testing
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus сам себя
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # QUIC Client метрики
  - job_name: 'quic-client'
    static_configs:
      - targets: ['quic-client:2112']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # QUIC Server метрики
  - job_name: 'quic-server'
    static_configs:
      - targets: ['quic-server:2113']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Dashboard метрики (если есть)
  - job_name: 'dashboard'
    static_configs:
      - targets: ['dashboard:9990']
    scrape_interval: 10s
    metrics_path: '/metrics'

  # Node Exporter (если добавлен)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: '/metrics'
    # Отключено по умолчанию, раскомментировать при необходимости
    # scrape_configs:
