# 2GC Network Protocol Suite - Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # QUIC Server metrics
  - job_name: 'quic-server'
    static_configs:
      - targets: ['2gc-network-server:2113']
    scrape_interval: 5s
    metrics_path: '/metrics'
    honor_labels: true

  # QUIC Client metrics  
  - job_name: 'quic-client'
    static_configs:
      - targets: ['2gc-network-client:2112']
    scrape_interval: 5s
    metrics_path: '/metrics'
    honor_labels: true

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter (if available)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 15s

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 15s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093